[[rewarders]]
id = "saber"
name = "Saber"
address = "rXhAofQCT7NN9TUqigyEAUzV1uLL4boeD8CRkNBSkYk"
networks = ["mainnet-beta", "devnet"]
color = "#6966FB"
description = "Saber is a protocol enabling seamless cross-chain liquidity exchange."
website = "https://saber.so"

[rewarders.redeemer]
underlyingToken = "Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1"
method = "saber"

[[rewarders]]
id = "lido_super_test"
name = "lido_super_test"
address = "58u68XDr3VF31PPssUM4MKWduXxWoYmZWdpGRz74Lhuo"
networks = ["devnet"]
color = "#6966FB"
description = "Lido test rewarder."
website = "https://saber.so"

[rewarders.redeemer]
underlyingToken = "bLpASoWNdsz5DsjCaxpbM2FrkMowTJCydpwiDP4Vdzm"
method = "saber"

[[rewarders]]
id = "saber-luna"
name = "Saber Luna Rewards"
address = "9eNj2Y4YdqM9Unw8qTm8kzx1Xt64Rft8a6HjvpkPL7QJ"
networks = ["mainnet-beta"]
color = "#6966FB"
description = "Luna rewards for Saber."
website = "https://saber.so"

[rewarders.redeemer]
underlyingToken = "F6v4wfAdJB8D8p77bMXZgYt8TDKsYxLYxH5AFhUkYx9W"
method = "quarry-redeemer"

[[rewarders]]
id = "sunny"
name = "Sunny Aggregator"
networks = ["mainnet-beta", "devnet"]
address = "97PmYbGpSHSrKrUkQX793mjpA2EA9rrQKkHsQuvenU44"
color = "#DC723F"
description = "Solana's cross-chain DeFi yield aggregator."
website = "https://sunny.ag"
hidden = true

[rewarders.redeemer]
underlyingToken = "SUNNYWgPQmFxe9wTZzNK7iPnJ3vYDrkgnxJRJm1s3ag"
method = "sunny"

[[rewarders]]
id = "larry-test"
name = "Larry's Testing Rewarder"
networks = ["devnet"]
address = "AaQnmceRh5phVdqYsH8QnoYeYPMvGm2PtYJoe2T3w5oE"
color = "#ffdc00"
description = "Larry is giving out fake and useless tokens on devnet."
website = "https://quarry.so"

[rewarders.redeemer]
underlyingToken = "2jmzZmwSnL9B6WRt9ZG1ayK8A2iQsNbvz3XR8KnXSheB"
method = "quarry-redeemer"

[[rewarders]]
id = "larry-test-other"
name = "Larry's Other Testing Rewarder"
networks = ["devnet"]
address = "BX6gJLjmviXQVuqxJB3V5mVEKvhD6k7ffc2UjdwcgNR7"
color = "#00ffff"
description = "Larry is giving out more fake and useless tokens on devnet."
website = "https://quarry.so"

[[rewarders]]
id = "marinade"
name = "Marinade"
networks = ["mainnet-beta", "devnet"]
address = "J829VB5Fi7DMoMLK7bsVGFM82cRU61BKtiPz9PNFdL7b"
color = "#EF39F8"
description = "The easiest way to stake Solana."
website = "https://marinade.finance"

[rewarders.redeemer]
underlyingToken = "MNDEFzGvMt87ueuHvVU9VcTqsAP5b3fTGPsHuuPA5ey"
method = "marinade"

[[rewarders]]
id = "cash-cow"
name = "Cash Cow"
networks = ["mainnet-beta"]
address = "5LAZ5rUe1CLJoKYauyVXdbG6e7nBmY2j5mJ8PnesCA8z"
color = "#01EB00"
description = "Cashio’s fair launch memecoin"
website = "https://cashio.app"

[[rewarders]]
id = "saber-mnde"
name = "Saber Marinade Rewards"
networks = ["mainnet-beta"]
address = "CduAhHmZe3n5KkxhP4EjqTZjWTuptYnfXvi4ULyF7fVc"
color = "#6966FB"
description = "Marinade rewards for Saber."
website = "https://saber.so"

[rewarders.redeemer]
underlyingToken = "MNDEFzGvMt87ueuHvVU9VcTqsAP5b3fTGPsHuuPA5ey"
method = "quarry-redeemer"

[[rewarders]]
id = "saber-lido"
name = "Saber Lido Rewards"
networks = ["mainnet-beta"]
address = "CXer5v3osVQFDWUB3SJUPB1PN1dB3dQSQfymyAnmCryp"
color = "#6966FB"
description = "Lido rewards for Saber."
website = "https://lido.fi/solana"

[rewarders.redeemer]
underlyingToken = "HZRCwxP2Vq9PCpPXooayhJ2bxTpo5xfpQrwB1svh332p"
method = "quarry-redeemer"

[[rewarders]]
id = "saber-lido-legacy"
name = "Saber Lido Rewards"
networks = ["mainnet-beta"]
address = "3UqiNcE1S2MoQ1M1PvrQf3gCkM7KB1nWfZdoQckobHpz"
color = "#6966FB"
description = "Lido rewards for Saber."
website = "https://saber.so"

[rewarders.redeemer]
underlyingToken = "HZRCwxP2Vq9PCpPXooayhJ2bxTpo5xfpQrwB1svh332p"
method = "quarry-redeemer"

[[rewarders]]
id = "pole"
name = "Pole Aggregator"
networks = ["mainnet-beta"]
address = "3ahWtCwoyv4HHYdDtSzSPzD8DDo6jJKqEmPJrdztFnw4"
color = "#8d459a"
description = "Pole Finance is a leveraged yield aggregator on Solana."
website = "https://pole.finance/"

[rewarders.redeemer]
underlyingToken = "PoLEXM5xikzieXENFvP7WwHJPorcFiCUVuMo9BAGZT3"
method = "quarry-redeemer"

[[rewarders]]
id = "port"
name = "Port Finance"
networks = ["mainnet-beta"]
address = "GuHrjvzqDvLTB27ebd9iFKwceCxKvSswzTByDQUTsvdm"
color = "#806df9"
description = "Port Finance aims to provide a suite of fixed income products."
website = "https://port.finance"

[rewarders.redeemer]
underlyingToken = "PoRTjZMPXb9T7dyU7tpLEZRQj7e6ssfAE62j2oQuc6y"
method = "quarry-redeemer"

[[rewarders]]
id = "swim-devnet"
name = "Swim Protocol Devnet"
networks = ["devnet"]
address = "HCW7URopNHQHB9sdPP2vx5uUu3pU19FVSy9AG2sZB1GM"
color = "#277CE2"
description = "Swim Protocol is a seamless multi-chain liquidity protocol"
website = "https://swim.io"

[rewarders.redeemer]
underlyingToken = "G2Ftt9yakMXgbHP3r5fzGScctG9kXPEbKHPvJn11M3s3"
method = "quarry-redeemer"

[[rewarders]]
id = "swim"
name = "Swim Protocol"
networks = ["devnet"]
address = "AJzYc9R3JbianR26aJkTJ3Xz9GLbAS8zJDjcivPmoaja"
color = "#277CE2"
description = "Swim Protocol is a seamless multi-chain liquidity protocol"
website = "https://swim.io"

[rewarders.redeemer]
underlyingToken = "swimnKEr963p7EbCjsSnBCoYwytuZHPm3zbq6fKLHXb"
method = "quarry-redeemer"

[[rewarders]]
id = "saber-hubb"
name = "Saber Hubble Rewards"
networks = ["mainnet-beta"]
address = "Wz2Zzi5BHmYr75yNzJG8NZ8U1T9cSWKf6ATRwZF7qV6"
color = "#7a84ff"
description = "Hubble rewards for Saber."
website = "https://hubbleprotocol.io"

[rewarders.redeemer]
underlyingToken = "HBB111SCo9jkCejsZfz8Ec8nH7T6THF8KEKSnvwT6XK6"
method = "quarry-redeemer"

[[rewarders]]
id = "sentre-devnet"
name = "Sentre Protocol"
networks = ["devnet"]
address = "2ZP24TRHo5fJMdLuiTSzzpPfFcjkCtML4wxeRNWgwprP"
color = "#ff0000"
description = "Sentre dummy des"
website = "https://sentre.io"

[rewarders.redeemer]
underlyingToken = "5YwUkPdXLoujGkZuo9B4LsLKj3hdkDcfP4derpspifSJ"
method = "quarry-redeemer"

[[rewarders]]
id = "sentre"
name = "Sentre Protocol"
networks = ["mainnet-beta"]
address = "9JrJzACR6MbqXdBPKD5YPUEVbxaC3KeHZEymafkw5VYw"
color = "#f9575e"
description = "All-in-One Solana Open Platform with DApps Store and Universal Protocol for Liquidity."
website = "https://sentre.io"

[rewarders.redeemer]
underlyingToken = "SENBBKVCM7homnf5RX9zqpf1GFe935hnbU4uVzY1Y6M"
method = "quarry-redeemer"

[[rewarders]]
id = "Jungle"
name = "Jungle Finance"
networks = ["mainnet-beta"]
address = "HsryAVAm1TA917GuGc1h6fcjBLd1gnUoEfjzQs688DAx"
color = "#00ff0a"
description = "Jungle Finance Governance Token"
website = "https://jungledefi.io"

[rewarders.redeemer]
underlyingToken = "GePFQaZKHcWE5vpxHfviQtH5jgxokSs51Y5Q4zgBiMDs"
method = "quarry-redeemer"

[[rewarders]]
id = "saber-frax"
name = "Saber Frax Rewards"
networks = ["mainnet-beta"]
address = "2UsGfm8S36eW58U4JeKgVC9fcXsqf7D6vfm4GHUtnENn"
color = "#6966FB"
description = "Frax rewards for Saber."
website = "https://saber.so"
prelaunch = true

[rewarders.redeemer]
underlyingToken = "6LX8BhMQ4Sy2otmAWj7Y5sKd9YTVVUgfMsBzT6B9W7ct"
method = "quarry-redeemer"

[[rewarders]]
id = "soluna"
name = "Soluna"
address = "AnYPEy4H3U3XhT5hwM4cGPxLk3CNqn9kkqzyaXhj1LKc"
networks = ["mainnet-beta"]
color = "#FEAB53"
description = "The gateway to Anchor interest bearing assets on Solana."
website = "https://soluna.money"
